server:
  port: 8001
 
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runsMillis: 60000
      min-evictable-idle-timeMillis: 300000
      validation-query: select 'x' FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true
  thymeleaf:
     mode: LEGACYHTML5
     prefix: classpath:/templates/
     suffix: .html
     encoding: UTF-8
     cache: false
  mvc:
    view:
     suffix: .html
  redis:
    host: 120.78.88.153
    port: 6379
 
mybatis:
  # Mapper文件位置
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hd.entity
  # Mybatis配置文件位置
  #config-location: classpath:config/mybatis-config.xml

# springboot默认日志实现：logback
logging:
  pattern:
    console: "%d - %msg%n"
  level:
    # 这里可以是包名也可以是类名
    # DEBUG<INFO<WARN<ERROR<FATAL
    com.hd: debug
    com.hd.dao: debug
  file: e:/log.txt  # 日志文件输出