server:
  port: 8080
 
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://120.78.88.153:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runsMillis: 60000
      min-evictable-idle-timeMillis: 300000
      validation-query: select 'x' FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true
  thymeleaf:
     mode: LEGACYHTML5
     prefix: classpath:/templates/
     suffix: .html
     encoding: UTF-8
     cache: false
  mvc:
    view:
     suffix: .html
  redis:
    host: 120.78.88.153
    port: 6379
 
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hd.entity
#showSql
logging:
  level:
    com:
      hd:
        dao : debug